///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsBarlowBlack = 'assets/fonts/Barlow-Black.ttf';
  static const String fontsBarlowBlackItalic = 'assets/fonts/Barlow-BlackItalic.ttf';
  static const String fontsBarlowBold = 'assets/fonts/Barlow-Bold.ttf';
  static const String fontsBarlowBoldItalic = 'assets/fonts/Barlow-BoldItalic.ttf';
  static const String fontsBarlowExtraBold = 'assets/fonts/Barlow-ExtraBold.ttf';
  static const String fontsBarlowExtraBoldItalic = 'assets/fonts/Barlow-ExtraBoldItalic.ttf';
  static const String fontsBarlowExtraLight = 'assets/fonts/Barlow-ExtraLight.ttf';
  static const String fontsBarlowExtraLightItalic = 'assets/fonts/Barlow-ExtraLightItalic.ttf';
  static const String fontsBarlowItalic = 'assets/fonts/Barlow-Italic.ttf';
  static const String fontsBarlowLight = 'assets/fonts/Barlow-Light.ttf';
  static const String fontsBarlowLightItalic = 'assets/fonts/Barlow-LightItalic.ttf';
  static const String fontsBarlowMedium = 'assets/fonts/Barlow-Medium.ttf';
  static const String fontsBarlowMediumItalic = 'assets/fonts/Barlow-MediumItalic.ttf';
  static const String fontsBarlowRegular = 'assets/fonts/Barlow-Regular.ttf';
  static const String fontsBarlowSemiBold = 'assets/fonts/Barlow-SemiBold.ttf';
  static const String fontsBarlowSemiBoldItalic = 'assets/fonts/Barlow-SemiBoldItalic.ttf';
  static const String fontsBarlowThin = 'assets/fonts/Barlow-Thin.ttf';
  static const String fontsBarlowThinItalic = 'assets/fonts/Barlow-ThinItalic.ttf';
  static const String fontsOFL = 'assets/fonts/OFL.txt';
  static const String globalApple = 'assets/icons/global/apple.svg';
  static const String globalCalendar = 'assets/icons/global/calendar.svg';
  static const String globalCreate = 'assets/icons/global/create.svg';
  static const String globalExpense = 'assets/icons/global/expense.svg';
  static const String globalEyeOff = 'assets/icons/global/eye_off.svg';
  static const String globalEyeOn = 'assets/icons/global/eye_on.svg';
  static const String globalFacebook = 'assets/icons/global/facebook.svg';
  static const String globalGoogle = 'assets/icons/global/google.svg';
  static const String globalLogo = 'assets/icons/global/logo.svg';
  static const String globalStats = 'assets/icons/global/stats.svg';
  static const String globalTasks = 'assets/icons/global/tasks.svg';
  static const String imagesOnboarding = 'assets/images/onboarding.png';
  static const String imagesOnboarding1 = 'assets/images/onboarding1.png';
  static const String tasksFilter = 'assets/icons/tasks/filter.svg';
  static const String tasksHamburger = 'assets/icons/tasks/hamburger.svg';
  static const String tasksNote = 'assets/icons/tasks/note.svg';
  static const String tasksNotification = 'assets/icons/tasks/notification.svg';
  static const String tasksSearch = 'assets/icons/tasks/search.svg';

}
